- hosts: all
  become: yes
  tasks:

  - name: Install Java
    apt:
      name: openjdk-11-jdk
      state: present

  - name: Creating Apache Tomcat home directory.
    command: mkdir /opt/tomcat

  - name: Download Tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz
      dest: /opt/

  - name: Extract tar.gz
    shell: tar -xzvf /opt/apache-tomcat-9.0.85.tar.gz -C /opt/tomcat --strip-components=1

  - name: Replace a line
    lineinfile:
      path: /opt/tomcat/conf/server.xml
      regexp: <Connector port="8080" protocol="HTTP/1.1"
      line: <Connector port="8081" protocol="HTTP/1.1"

  - name: Start Tomcat
    shell: /opt/tomcat/bin/startup.sh

  - name: Replace a line
    lineinfile:
      path: /opt/tomcat/conf/server.xml
      regexp: <Connector port="8080" protocol="HTTP/1.1"
      line: <Connector port="8081" protocol="HTTP/1.1"

  - name: Stop Tomcat
    shell: /opt/tomcat/bin/shutdown.sh

  - name: Start Tomcat
    shell: /opt/tomcat/bin/startup.sh

# nano /opt/tomcat/webapps/manager/META-INF/context.xml - comment one file
# nano /opt/tomcat/conf/tomcat-users.xml -add <role rolename="manager-gui"/>
#  <user username="tomcat" password="tomcat" roles="manager-gui"/>





